export type Lang = "tr" | "en";

export const content = {
  en: {
    hero: {
      title: "The Ultimate Theme Switcher",
      titleLine1: "Theme Switching",
      titleLine2: "Made Simple",
      subtitle:
        "Type-safe, modular, and instant theme switching for React & Tailwind CSS v4.",
      cta: "Get Started",
      install: "npm install reactive-switcher",
      typescript: "TypeScript",
      fullSupport: "Full Support",
      tailwindV4: "Tailwind v4",
      ready: "Ready",
      gzipped: "Gzipped",
      noFlash: "No Flash!",
    },
    features: {
      instant: {
        title: "Instant Switching",
        desc: "Zero runtime overhead. Themes switch instantly using CSS variables.",
      },
      types: {
        title: "Fully Typed",
        desc: "TypeScript support out of the box. Autocomplete your theme tokens.",
      },
      tailwind: {
        title: "Tailwind v4 Ready",
        desc: "Seamless integration with the new Tailwind CSS engine.",
      },
    },
    demo: {
      title: "Live Playground",
      desc: "Try clicking the themes below. This entire page uses the library.",
      current: "Active Theme",
    },
    usage: {
      title: "How it works",
      step1: "1. Define your theme",
      step2: "2. Wrap your app",
      step3: "3. Use the hook",
    },
    navbar: {
      features: "Features",
      showcase: "Showcase",
      docs: "Docs",
      theme: "Theme",
      starOnGithub: "Star on GitHub",
    },
    footer: {
      description:
        "Type-safe, modular, and instant theme switching for React & Tailwind CSS v4. Zero runtime overhead.",
      product: "Product",
      documentation: "Documentation",
      showcase: "Showcase",
      features: "Features",
      changelog: "Changelog",
      resources: "Resources",
      github: "GitHub",
      npmPackage: "NPM Package",
      blog: "Blog",
      community: "Community",
      twitter: "Twitter",
      buyMeACoffee: "Buy me a coffee",
      mitLicense: "MIT License",
      builtWith: "Built with",
      using: "using",
      starOnGithub: "Star on GitHub",
    },
    showcase: {
      interactiveDemo: "Interactive Demo",
      scopedTheming: "Scoped Theming",
      scopedDesc:
        "This demo uses isolated theming. Changes only affect the preview panel, not the main page.",
      lightMode: "Light Mode",
      darkMode: "Dark Mode",
      oceanMode: "Ocean Mode",
      dashboard: "Dashboard",
      welcomeBack: "Welcome back, Developer",
      newProject: "New Project",
      totalUsers: "Total Users",
      activeNow: "Active Now",
      revenue: "Revenue",
      recentActivity: "Recent Activity",
      viewAll: "View All",
      quickActions: "Quick Actions",
      createPost: "Create Post",
      uploadFile: "Upload File",
      sendEmail: "Send Email",
      minutesAgo: "m ago",
    },
    cta: {
      title: "Ready to Get Started?",
      description:
        "Add beautiful, customizable themes to your React app in just a few minutes. It's free and open source.",
      readDocs: "Read the Docs",
      viewOnGithub: "View on GitHub",
      gzipped: "Gzipped",
      licensed: "Licensed",
    },
  },
  tr: {
    hero: {
      title: "En İyi Tema Yönetimi",
      titleLine1: "Tema Değiştirme",
      titleLine2: "Artık Çok Kolay",
      subtitle:
        "React ve Tailwind CSS v4 için tip güvenli, modüler ve anlık tema değiştirici.",
      cta: "Başlayın",
      install: "npm install reactive-switcher",
      typescript: "TypeScript",
      fullSupport: "Tam Destek",
      tailwindV4: "Tailwind v4",
      ready: "Uyumlu",
      gzipped: "Sıkıştırılmış",
      noFlash: "Flash Yok!",
    },
    features: {
      instant: {
        title: "Anlık Geçiş",
        desc: "Sıfır performans kaybı. CSS değişkenleri ile milisaniyeler içinde değişim.",
      },
      types: {
        title: "Tam Tip Desteği",
        desc: "Kutudan çıktığı gibi TypeScript desteği. Renklerinizi otomatik tamamlayın.",
      },
      tailwind: {
        title: "Tailwind v4 Uyumlu",
        desc: "Yeni Tailwind CSS motoru ile kusursuz entegrasyon.",
      },
    },
    demo: {
      title: "Canlı Demo",
      desc: "Aşağıdaki temalara tıklayın. Bu sayfa tamamen bu kütüphane ile çalışıyor.",
      current: "Aktif Tema",
    },
    usage: {
      title: "Nasıl Çalışır?",
      step1: "1. Temanızı tanımlayın",
      step2: "2. Uygulamayı sarmalayın",
      step3: "3. Hook'u kullanın",
    },
    navbar: {
      features: "Özellikler",
      showcase: "Demo",
      docs: "Döküman",
      theme: "Tema",
      starOnGithub: "GitHub'da Yıldızla",
    },
    footer: {
      description:
        "React ve Tailwind CSS v4 için tip güvenli, modüler ve anlık tema değiştirici. Sıfır çalışma zamanı yükü.",
      product: "Ürün",
      documentation: "Dokümantasyon",
      showcase: "Demo",
      features: "Özellikler",
      changelog: "Değişiklik Günlüğü",
      resources: "Kaynaklar",
      github: "GitHub",
      npmPackage: "NPM Paketi",
      blog: "Blog",
      community: "Topluluk",
      twitter: "Twitter",
      buyMeACoffee: "Bana kahve ısmarla",
      mitLicense: "MIT Lisansı",
      builtWith: "ile yapıldı",
      using: "kullanılarak",
      starOnGithub: "GitHub'da Yıldızla",
    },
    showcase: {
      interactiveDemo: "İnteraktif Demo",
      scopedTheming: "Kapsamlı Tema",
      scopedDesc:
        "Bu demo izole tema kullanır. Değişiklikler sadece önizleme panelini etkiler, ana sayfayı değil.",
      lightMode: "Açık Mod",
      darkMode: "Koyu Mod",
      oceanMode: "Okyanus Modu",
      dashboard: "Kontrol Paneli",
      welcomeBack: "Tekrar hoş geldin, Geliştirici",
      newProject: "Yeni Proje",
      totalUsers: "Toplam Kullanıcı",
      activeNow: "Şu An Aktif",
      revenue: "Gelir",
      recentActivity: "Son Aktiviteler",
      viewAll: "Tümünü Gör",
      quickActions: "Hızlı Eylemler",
      createPost: "Gönderi Oluştur",
      uploadFile: "Dosya Yükle",
      sendEmail: "E-posta Gönder",
      minutesAgo: "dk önce",
    },
    cta: {
      title: "Başlamaya Hazır mısınız?",
      description:
        "React uygulamanıza birkaç dakika içinde güzel, özelleştirilebilir temalar ekleyin. Ücretsiz ve açık kaynak.",
      readDocs: "Dökümantasyonu Oku",
      viewOnGithub: "GitHub'da Görüntüle",
      gzipped: "Sıkıştırılmış",
      licensed: "Lisanslı",
    },
  },
};
